In [2]:
import numpy as np

In [14]:
X = np.random.normal(1, 0.1, (2, 2))

In [15]:
X

array([[0.96760836, 0.86405176],
       [1.16634568, 0.97419729]])

In [16]:
X.T

array([[0.96760836, 1.16634568],
       [0.86405176, 0.97419729]])

In [17]:
Y = [[1, -1], [-1, 1]]

In [20]:
Y = np.array(Y)

In [22]:
Y.shape

(2, 2)

In [24]:
Y.dot(np.array([1, 2]))

array([-1,  1])

In [25]:
Y @ np.array([1, 2])

array([-1,  1])

In [27]:
np.random.normal(1, 2, (1, 2))

array([[-5.09460376, -1.80363271]])