In [1]:
import numpy as np

In [2]:
X = np.random.normal(1, 0.1, (2, 2))

In [3]:
X

array([[0.96302448, 1.08599402],
       [0.8910803 , 1.09329819]])

In [4]:
X.T

array([[0.96302448, 0.8910803 ],
       [1.08599402, 1.09329819]])

In [5]:
Y = [[1, -1], [-1, 1]]

In [6]:
Y = np.array(Y)

In [7]:
Y.shape

(2, 2)

In [8]:
Y.dot(np.array([1, 2]))

array([-1,  1])

In [9]:
Y @ np.array([1, 2])

array([-1,  1])

In [10]:
np.random.normal(1, 2, (1, 2))

array([[1.29593099, 1.21816555]])

In [13]:
X = np.random.normal(1, 0.1, (10, 10))

In [14]:
X

array([[1.10504471, 0.98847684, 1.18680779, 0.77180137, 1.05866402,
        0.93814299, 1.07524432, 0.9358891 , 0.99909542, 1.06412234],
       [1.01769983, 0.91585219, 1.04176568, 1.15426367, 0.92932166,
        0.9492168 , 0.81326528, 1.13127419, 0.95343845, 1.07675897],
       [1.1910488 , 1.02678333, 0.91944146, 0.86980488, 0.88838745,
        0.94483295, 0.95517761, 0.83151933, 0.92870634, 0.895649  ],
       [0.94945856, 1.07289372, 0.75878951, 1.01736415, 1.00085889,
        1.05560335, 0.96037295, 0.99480216, 0.89792612, 1.04980235],
       [1.03297358, 0.9732736 , 0.94807   , 0.9950825 , 0.87831976,
        0.88137686, 0.77451181, 0.89793097, 0.9934011 , 0.89738568],
       [0.98604282, 1.08734215, 1.05817181, 1.08077592, 1.21886826,
        1.11263375, 1.03119901, 0.83945937, 1.01396369, 0.96924138],
       [0.89057843, 0.90593595, 1.13092562, 1.05280918, 0.95443437,
        0.96802238, 1.02067359, 1.11615964, 1.14396341, 0.94777394],
       [0.87210063, 1.09027646, 0.9584520

In [21]:
X

array([[1.10504471, 0.98847684, 1.18680779, 0.77180137, 1.05866402,
        0.93814299, 1.07524432, 0.9358891 , 0.99909542, 1.06412234],
       [1.01769983, 0.91585219, 1.04176568, 1.15426367, 0.92932166,
        0.9492168 , 0.81326528, 1.13127419, 0.95343845, 1.07675897],
       [1.1910488 , 1.02678333, 0.91944146, 0.86980488, 0.88838745,
        0.94483295, 0.95517761, 0.83151933, 0.92870634, 0.895649  ],
       [0.94945856, 1.07289372, 0.75878951, 1.01736415, 1.00085889,
        1.05560335, 0.96037295, 0.99480216, 0.89792612, 1.04980235],
       [1.03297358, 0.9732736 , 0.94807   , 0.9950825 , 0.87831976,
        0.88137686, 0.77451181, 0.89793097, 0.9934011 , 0.89738568],
       [0.98604282, 1.08734215, 1.05817181, 1.08077592, 1.21886826,
        1.11263375, 1.03119901, 0.83945937, 1.01396369, 0.96924138],
       [0.89057843, 0.90593595, 1.13092562, 1.05280918, 0.95443437,
        0.96802238, 1.02067359, 1.11615964, 1.14396341, 0.94777394],
       [0.87210063, 1.09027646, 0.9584520

In [18]:
1 / ( 1 + np.exp(-X))

array([[0.75120414, 0.72878697, 0.76616965, 0.68391044, 0.74243516,
        0.7187244 , 0.74559296, 0.71826853, 0.73088069, 0.74347754],
       [0.73452431, 0.71419621, 0.73919055, 0.76028883, 0.71693765,
        0.72095764, 0.69280488, 0.75607397, 0.72180615, 0.74588016],
       [0.76692859, 0.7362918 , 0.71492829, 0.7047051 , 0.70855729,
        0.72007486, 0.72215524, 0.69667609, 0.71681276, 0.71005455],
       [0.72100628, 0.74514683, 0.68109087, 0.73445885, 0.73122741,
        0.74184944, 0.72319647, 0.73003539, 0.71052313, 0.74073694],
       [0.73749198, 0.72577152, 0.72072687, 0.73009064, 0.70647391,
        0.70710746, 0.68449608, 0.71052413, 0.72975918, 0.71041196],
       [0.7283056 , 0.7478809 , 0.74234102, 0.74664079, 0.77186432,
        0.7526198 , 0.73714828, 0.69835134, 0.73379513, 0.72496826],
       [0.70900953, 0.71216781, 0.75600968, 0.74131397, 0.72200609,
        0.72472514, 0.73510379, 0.75327567, 0.75840658, 0.72066728],
       [0.70518261, 0.74843378, 0.7228117

In [20]:
X * X

array([[1.22112381, 0.97708647, 1.40851273, 0.59567735, 1.12076952,
        0.88011227, 1.15615035, 0.8758884 , 0.99819166, 1.13235636],
       [1.03571295, 0.83878523, 1.08527574, 1.33232463, 0.86363875,
        0.90101253, 0.66140041, 1.27978129, 0.90904487, 1.15940988],
       [1.41859725, 1.05428401, 0.8453726 , 0.75656052, 0.78923227,
        0.8927093 , 0.91236427, 0.6914244 , 0.86249546, 0.80218713],
       [0.90147156, 1.15110094, 0.57576152, 1.03502981, 1.00171851,
        1.11429844, 0.9223162 , 0.98963134, 0.80627132, 1.10208497],
       [1.06703442, 0.94726151, 0.89883673, 0.99018918, 0.7714456 ,
        0.77682516, 0.59986854, 0.80628003, 0.98684575, 0.80530106],
       [0.97228045, 1.18231296, 1.11972759, 1.1680766 , 1.48563983,
        1.23795386, 1.0633714 , 0.70469203, 1.02812237, 0.93942885],
       [0.79312994, 0.82071995, 1.27899275, 1.10840717, 0.91094496,
        0.93706732, 1.04177458, 1.24581234, 1.30865229, 0.89827543],
       [0.76055951, 1.18870276, 0.9186303